# Generated by Django 5.1.4 on 2024-12-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('AttendanceDataID', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('StudentID', models.CharField(default=0, max_length=20)),
                ('Subject_Name', models.CharField(default=0, max_length=30)),
                ('Subject_Code', models.CharField(default=0, max_length=30)),
                ('TeacherID', models.CharField(default=0, max_length=20)),
                ('CollageCode', models.CharField(default=0, max_length=30)),
                ('AttendanceTime', models.TimeField(blank=True, null=True)),
                ('AttendanceDay', models.CharField(default=0, max_length=20)),
                ('AttendanceDate', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseAdministratorList',
            fields=[
                ('DatabaseAdministratorID', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('DatabaseAdministrator_Name', models.CharField(default=0, max_length=30)),
                ('DatabaseAdministrator_Code', models.CharField(default=0, max_length=30)),
                ('DatabaseAdministrator_CollageCode', models.CharField(default=0, max_length=30)),
                ('DatabaseAdministrator_Email', models.EmailField(default=0, max_length=254, unique=True)),
                ('DatabaseAdministrator_Mobile', models.CharField(default=0, max_length=10, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('LoginStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentandSemestre',
            fields=[
                ('DepartmentandSemestreID', models.CharField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('Department_Code', models.CharField(default=0, max_length=150)),
                ('Department_Name', models.CharField(default=0, max_length=20)),
                ('Semestre', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('StudentID', models.CharField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default=0, max_length=150)),
                ('CollageCode', models.CharField(default=0, max_length=30)),
                ('Semestre', models.CharField(default=0, max_length=5)),
                ('Department', models.CharField(default=0, max_length=20)),
                ('Email', models.EmailField(default=0, max_length=254, unique=True)),
                ('Mobile', models.CharField(default=0, max_length=10, null=True, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Profile_Photo', models.ImageField(blank=True, default='Student_Profile_Photos/default-profile.png', null=True, upload_to='Student_Profile_Photos/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('StudentID', models.CharField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(default=0, max_length=150)),
                ('CollageCode', models.CharField(default=0, max_length=30)),
                ('Department', models.CharField(default=0, max_length=20)),
                ('DateOfBirth', models.DateField(default=0, null=True)),
                ('Email', models.EmailField(default=0, max_length=254, unique=True)),
                ('Mobile', models.CharField(default=0, max_length=10, unique=True)),
                ('RegistrationDate', models.DateField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectData',
            fields=[
                ('SubjectDataID', models.CharField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('Subject_Name', models.CharField(default=0, max_length=150)),
                ('Subject_Code', models.CharField(default=0, max_length=30)),
                ('Department', models.CharField(default=0, max_length=20)),
                ('Semestre', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('TeacherID', models.CharField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('Teacher_Name', models.CharField(default=0, max_length=150)),
                ('CollageCode', models.CharField(default=0, max_length=30)),
                ('Department', models.CharField(default=0, max_length=20)),
                ('Email', models.EmailField(default=0, max_length=254, unique=True)),
                ('Mobile', models.CharField(default=0, max_length=10, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Profile_Photo', models.ImageField(blank=True, default='Teacher_Profile_Photos/default-profile.png', null=True, upload_to='Teacher_Profile_Photos/')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLectureData',
            fields=[
                ('TeacherLectureDataID', models.CharField(default=0, max_length=20, primary_key=True, serialize=False)),
                ('TeacherID', models.CharField(default=0, max_length=20)),
                ('Teacher_Name', models.CharField(default=0, max_length=150)),
                ('Department', models.CharField(default=0, max_length=20)),
                ('Semestre', models.CharField(default=0, max_length=10)),
                ('Subject_Name', models.CharField(default=0, max_length=30)),
                ('Subject_Code', models.CharField(default=0, max_length=30)),
                ('LectureDate', models.DateField(default=0)),
                ('LectureDay', models.CharField(default=0, max_length=20)),
                ('LectureTime', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
