# Generated by Django 5.1.4 on 2024-12-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceattendancesystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlecturedata',
            name='LectureEndingTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherlecturedata',
            name='LectureStartingTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
