# Generated by Django 5.1.4 on 2025-04-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceattendancesystem', '0002_teacherlecturedata_lectureendingtime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancedata',
            unique_together={('StudentID', 'Subject_Name', 'AttendanceDate', 'AttendanceTime')},
        ),
    ]
